doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: App\DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false